packages:
  - '../cli'
  - '../../packages/agent-gateway-client'
  - '../../packages/const'
  - '../../packages/electron-server-ipc'
  - '../../packages/electron-client-ipc'
  - '../../packages/file-loaders'
  - '../../packages/desktop-bridge'
  - '../../packages/device-gateway-client'
  - '../../packages/local-file-shell'
  - './stubs/business-const'
  - './stubs/types'
  - '.'

lockfile: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true

publicHoistPattern:
  - '*@umijs/lint*'
  - '*unicorn*'
  - '*changelog*'
  - '*commitlint*'
  - '*eslint*'
  - '*postcss*'
  - '*prettier*'
  - '*remark*'
  - '*semantic-release*'
  - '*stylelint*'
  - '@auth/core'
  - 'pdfjs-dist'

allowBuilds:
  '@napi-rs/canvas': true
  'electron': true
  'electron-builder': true
  'electron-winstaller': true
  'esbuild': true
  'get-windows': true
  'node-mac-permissions': true

overrides:
  'react': 19.2.4
  'react-dom': 19.2.4
