packages:
  - '../../packages/agent-gateway-client'
  - '../../packages/device-gateway-client'
  - '../../packages/local-file-shell'
  - '../../packages/file-loaders'
  - '.'

lockfile: false
ignoreWorkspaceRootCheck: true

publicHoistPattern:
  - '*@umijs/lint*'
  - '*unicorn*'
  - '*changelog*'
  - '*commitlint*'
  - '*eslint*'
  - '*postcss*'
  - '*prettier*'
  - '*remark*'
  - '*semantic-release*'
  - '*stylelint*'
