name: Desktop Build Setup
description: Setup Node.js, pnpm and install dependencies for desktop build

inputs:
  node-version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - name: Setup environment
      uses: ./.github/actions/setup-env
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --node-linker=hoisted --config.enable-global-virtual-store=false
      env:
        NODE_OPTIONS: --max-old-space-size=8192

    - name: Install deps on Desktop
      shell: bash
      run: pnpm --dir ./apps/desktop install --node-linker=hoisted --config.enable-global-virtual-store=false
      env:
        NODE_OPTIONS: --max-old-space-size=8192
